# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='歌曲名')),
                ('url', models.CharField(max_length=256, verbose_name='歌曲资源URL')),
            ],
            options={
                'verbose_name_plural': '歌单歌曲',
            },
        ),
        migrations.CreateModel(
            name='SongsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='歌单名')),
                ('list_id', models.CharField(max_length=24, verbose_name='歌单id')),
                ('pic', models.CharField(max_length=256, verbose_name='歌单图片链接')),
                ('date', models.DateField(auto_now=True, verbose_name='歌单创建日期')),
                ('Class', models.CharField(max_length=32, verbose_name='歌单类型')),
            ],
            options={
                'verbose_name_plural': '歌单',
            },
        ),
        migrations.AddField(
            model_name='songs',
            name='songslist',
            field=models.ManyToManyField(to='songslist.SongsList'),
        ),
    ]
