# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songslist', '0005_songslist_listen_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songslist',
            name='listen_times',
            field=models.IntegerField(verbose_name='播放量'),
        ),
    ]
