# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songsrank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyin_song_rank',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='歌曲长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot_song_rank',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='歌曲长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_song_rank',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='歌曲长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular_song_rank',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='歌曲长度'),
            preserve_default=False,
        ),
    ]
