# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsrank', '0002_auto_20181001_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dianjing_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': '电竞音乐榜',
            },
        ),
        migrations.CreateModel(
            name='Dianyin_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': '电音排行榜',
            },
        ),
        migrations.CreateModel(
            name='KTV_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': 'KTV唛榜',
            },
        ),
    ]
