# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsrank', '0003_dianjing_song_rank_dianyin_song_rank_ktv_song_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': '美国BillBoard榜',
            },
        ),
        migrations.CreateModel(
            name='Oricon_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': '日本Oricon周榜',
            },
        ),
        migrations.CreateModel(
            name='Q_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': '英国Q杂志中文版周榜',
            },
        ),
        migrations.CreateModel(
            name='UK_Song_Rank',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌名')),
                ('singer', models.CharField(max_length=10, verbose_name='歌手')),
                ('album', models.CharField(max_length=32, verbose_name='专辑')),
                ('pic_url', models.CharField(max_length=256, verbose_name='歌曲专辑图片')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('duration', models.CharField(max_length=32, verbose_name='歌曲长度')),
            ],
            options={
                'verbose_name_plural': 'UK排行榜周榜',
            },
        ),
    ]
