# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllAlbum',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='专辑')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='专辑id')),
                ('image', models.CharField(max_length=256, verbose_name='专辑图片地址')),
            ],
            options={
                'verbose_name_plural': '专辑',
            },
        ),
        migrations.CreateModel(
            name='AllSinger',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='歌手')),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌手id')),
            ],
            options={
                'verbose_name_plural': '歌手',
            },
        ),
        migrations.CreateModel(
            name='AllSongs',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌曲名')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.AllSinger')),
            ],
            options={
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.AddField(
            model_name='allalbum',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.AllSinger'),
        ),
        migrations.AddField(
            model_name='allalbum',
            name='song',
            field=models.ManyToManyField(to='demo.AllSongs'),
        ),
    ]
