# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('name', models.CharField(max_length=64, verbose_name='歌曲名')),
                ('sing_url', models.CharField(max_length=256, verbose_name='歌曲链接')),
            ],
            options={
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.RenameModel(
            old_name='AllAlbum',
            new_name='Albums',
        ),
        migrations.RenameModel(
            old_name='AllSinger',
            new_name='Singers',
        ),
        migrations.RemoveField(
            model_name='allsongs',
            name='singer',
        ),
        migrations.AlterField(
            model_name='albums',
            name='song',
            field=models.ManyToManyField(to='demo.Songs'),
        ),
        migrations.DeleteModel(
            name='AllSongs',
        ),
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.ManyToManyField(to='demo.Singers'),
        ),
    ]
