# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180902_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='singers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
