# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_singers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='singers',
            name='singerid',
            field=models.CharField(default=1, max_length=24, verbose_name='歌手id'),
            preserve_default=False,
        ),
    ]
