# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_singers_singerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='sing_url',
            new_name='song_url',
        ),
        migrations.AddField(
            model_name='albums',
            name='albumid',
            field=models.CharField(default=1, max_length=32, verbose_name='专辑id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='songid',
            field=models.CharField(default=1, max_length=24, verbose_name='歌曲id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albums',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
