# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20180903_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='singer',
        ),
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.Singers'),
            preserve_default=False,
        ),
    ]
